type: LCC2020Dataset
root: data/LCC2020
pyramid_level: 3
train_split:
  split: train
  transform:
  - type: RandomResizedCrop
    height: 512
    width: 512
    scale: [0.7, 1.0]
    p: 1.0
  - type: HorizontalFlip
    p: 0.5
  - type: Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: ToTensorV2
test_split:
  split: valid
  transform:
  - type: Resize
    height: 512
    width: 512
  - type: Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: ToTensorV2
