defaults:
  - transform@train_split.transform: moco_v2
  - transform@test_split.transform: test_preset

type: UWFC
root: data/uwfc_2020
subset: 2
train_split:
  split: train
  sample_size: null
  sampling_method: stratified
test_split:
  split: val
