defaults:
  - dataset: imagenet
  - loss@trainer.loss: cross_entropy
  - optimizer@trainer.optimizer: adam
  - lr_scheduler@trainer.lr_scheduler: one_cycle_lr

type: ImageClassification
eval_only_at_end: False
evaluate: False
val_freq: 1
model:
  type: ResNet
  depth: 50
  num_classes: ???
dataloader:
  global_batch_size: 256
  num_workers: 4 # per GPU
trainer:
  base_lr: 8e-3
  base_lr_batch_size: 256
  num_epochs: 100
  use_lars: False
  step_freq: batch
  mixed_precision: true
  lr_scheduler:
    pct_start: 0.05
    final_div_factor: 5
