- type: Resize
  height: 256
  width: 256
  p: 1.0
- type: CenterCrop
  height: 224
  width: 224
  p: 1.0
- type: Normalize
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
- type: ToTensorV2
