- type: RandomResizedCrop
  height: 224
  width: 224
  scale: [0.2, 1.0]
  p: 1.0
- type: HorizontalFlip
  p: 0.5
- type: ColorJitter
  brightness: 0.4
  contrast: 0.4
  saturation: 0.4
  hue: 0
  p: 0.5
- type: Normalize
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
- type: CoarseDropout
  max_holes: 1
  max_height: 70
  max_width: 70
  min_height: 18
  min_width: 18
  p: 0.5
- type: ToTensorV2
